### ISSUE TITLE
bug: voice channel users appear in all servers

### ISSUE THREAD

**Issue by quadratini** [yinghaoawang/Discourse#5]
Server 1
![image](https://user-images.githubusercontent.com/26881851/227595518-86af558c-6f44-4d8e-8f3b-56bf581546eb.png)

Server 2
![image](https://user-images.githubusercontent.com/26881851/227595581-bc31f380-0e3f-4ee9-a95d-010c62563884.png)

**Comment by yinghaoawang** [comment]
Problem was that the voice channel naming scheme was changed, so all that was needed was to delete the server data.

**Comment by yinghaoawang** [comment]
> Problem was that the voice channel naming scheme was changed, so all that was needed was to delete the server data.

wasn't correct, still broken, fixed with this 7165e45c376cfd8d708510d56a1cff2f05149ef0
